steps:
# 1. Dockerイメージをビルドする
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:$SHORT_SHA',
    '.'
  ]

# 2. ビルドしたイメージをArtifact Registryにプッシュする
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:$SHORT_SHA'
  ]

# 3. 新しいイメージをCloud Runにデプロイする
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    '${_SERVICE_NAME}',
    '--image',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:$SHORT_SHA',
    '--region',
    '${_REGION}',
    '--platform',
    'managed',
    '--allow-unauthenticated',
    '--timeout=3600',
    '--set-env-vars=GCS_BUCKET_NAME=${_BUCKET_NAME}'
  ]

# ビルドしたイメージを保存
images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:$SHORT_SHA'
